<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['process_viewer_app_description'] = 'Средство просмотра Процесса предоставляет табличное отображение всех процессов, запущенных в системе. Конкретная информация о каждом процессе есть в списке, в том числе ID процесса, время работы центрального процессора и памяти.';
$lang['process_viewer_app_name'] = 'Просмотр процессов';
$lang['process_viewer_command'] = 'Команда';
$lang['process_viewer_cpu'] = 'CPU';
$lang['process_viewer_id'] = 'ID';
$lang['process_viewer_memory'] = 'Память';
$lang['process_viewer_owner'] = 'Владелец';
$lang['process_viewer_process'] = 'Процесс';
$lang['process_viewer_processes'] = 'Процессы';
$lang['process_viewer_running'] = 'Работает';
$lang['process_viewer_size'] = 'Размер';
