<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['process_viewer_app_description'] = 'Der Prozessmanager stellet alle laufenden Prozesse des Systems tabellarisch dar.  Es werden exakte Informationen zu jedem Prozess wie, ProzessID, Laufzeit, CPU- und Arbeitsspeicherauslastung, aufgelistet.';
$lang['process_viewer_app_name'] = 'Prozessmanager';
$lang['process_viewer_command'] = 'Befehl';
$lang['process_viewer_cpu'] = 'CPU';
$lang['process_viewer_id'] = 'ID';
$lang['process_viewer_memory'] = 'Arbeitsspeicher';
$lang['process_viewer_owner'] = 'Besitzer';
$lang['process_viewer_process'] = 'Prozess';
$lang['process_viewer_process_cpu_usage'] = 'Process CPU Usage';
$lang['process_viewer_process_memory_usage'] = 'Process Memory Usage';
$lang['process_viewer_processes'] = 'Prozesse';
$lang['process_viewer_running'] = 'Wird ausgeführt';
$lang['process_viewer_size'] = 'Größe';
