<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['process_viewer_app_description'] = 'O Visualizador de Processos fornece uma visão tabular de todos os processos em execução no sistema.  Informações específicas sobre cada processo é listado, incluindo ID do processo, tempo de execução, CPU e uso de memória.';
$lang['process_viewer_app_name'] = 'Visualizador de Processos';
$lang['process_viewer_command'] = 'Comando';
$lang['process_viewer_cpu'] = 'CPU';
$lang['process_viewer_id'] = 'ID';
$lang['process_viewer_memory'] = 'Memória';
$lang['process_viewer_owner'] = 'Proprietário';
$lang['process_viewer_process'] = 'Processo';
$lang['process_viewer_process_cpu_usage'] = 'Process CPU Usage';
$lang['process_viewer_process_memory_usage'] = 'Process Memory Usage';
$lang['process_viewer_processes'] = 'Processos';
$lang['process_viewer_running'] = 'Executando';
$lang['process_viewer_size'] = 'Tamanho';
