<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['process_viewer_app_description'] = 'Processvisaren ger en tabellvy över alla processer som körs på systemet.   Specifik information om varje process visas inklusive processID, körtid, CPU- och minnesanvändning.';
$lang['process_viewer_app_name'] = 'Processvisaren';
$lang['process_viewer_command'] = 'Kommando';
$lang['process_viewer_cpu'] = 'CPU';
$lang['process_viewer_id'] = 'ID';
$lang['process_viewer_memory'] = 'Minne';
$lang['process_viewer_owner'] = 'Ägare';
$lang['process_viewer_process'] = 'Process';
$lang['process_viewer_processes'] = 'Processer';
$lang['process_viewer_running'] = 'Körs';
$lang['process_viewer_size'] = 'Storlek';
