<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['process_viewer_app_description'] = 'Podgląd procesów umożliwia tabelaryczne wyświetlenie wszystkich procesów działających w systemie.  Dla każdego procesu pokazane są specyficzne informacje, np. ID procesu, czas pracy, użycie CPU oraz pamięci.';
$lang['process_viewer_app_name'] = 'Podgląd procesów';
$lang['process_viewer_command'] = 'Polecenie';
$lang['process_viewer_cpu'] = 'CPU';
$lang['process_viewer_id'] = 'ID';
$lang['process_viewer_memory'] = 'Pamięć';
$lang['process_viewer_owner'] = 'Właściciel';
$lang['process_viewer_process'] = 'Proces';
$lang['process_viewer_processes'] = 'Procesy';
$lang['process_viewer_running'] = 'Działające';
$lang['process_viewer_size'] = 'Rozmiar';
